#!/usr/bin/python3
# -*- coding: utf-8 -*-

from paho.mqtt.client import Client as MqttClient
from pyModbusTCP.client import ModbusClient
import threading
import signal
import time
import sys
import os


# modbus tcp server
MODBUS_HOST = 'mbusd'
MODBUS_PORT = 502

# mqtt broker
MQTT_HOST = 'mosquitto'
MQTT_PORT = 1883


def terminate(signum, frame):
    sys.exit(0)


def mqtt_connected(mqtt, userdata, flags, rc):
    if rc == 0:
        mqtt.subscribe('modbus2mqtt/coil/+/set')


def mqtt_received(mqtt, userdata, message):
    modbus, lock, n = userdata
    topic = message.topic.split('/')
    payload = message.payload

    if len(topic) != 4 or topic[0] != 'modbus2mqtt':
        return

    if topic[1] == 'coil' and topic[2].isdigit() and topic[3] == 'set' and payload in (b'0', b'1'):
        coil = int(topic[2])

        if coil < 0 or coil >= n:
            return

        with lock:
            if not modbus.is_open():
                modbus.open()

            modbus.write_single_coil(coil, bool(int(payload)))


def main(n):
    # create lock
    lock = threading.Lock()

    # create modbus client
    modbus = ModbusClient()
    modbus.host(MODBUS_HOST)
    modbus.port(MODBUS_PORT)

    # create mqtt client
    mqtt = MqttClient('modbus2mqtt')
    mqtt.on_message = mqtt_received
    mqtt.on_connect = mqtt_connected
    mqtt.user_data_set((modbus, lock, n))
    mqtt.connect_async(MQTT_HOST, port=MQTT_PORT)
    mqtt.loop_start()

    # n coils
    coils = [None] * n

    while True:
        time.sleep(0.25)

        with lock:
            if not modbus.is_open():
                modbus.open()

            data = modbus.read_coils(0, n)

        if not data or data == coils:
            continue

        for i in range(n):
            if coils[i] is None:
                state = b'1' if data[i] else b'0'
                mqtt.publish('modbus2mqtt/coil/%d' % (i, ), state, retain=True)
                coils[i] = data[i]
                continue

            if coils[i] and not data[i]:
                mqtt.publish('modbus2mqtt/coil/%d' % (i, ), b'0', retain=True)
                coils[i] = False
                continue

            if not coils[i] and data[i]:
                mqtt.publish('modbus2mqtt/coil/%d' % (i, ), b'1', retain=True)
                coils[i] = True
                continue


if __name__ == '__main__':
    if os.getenv('MQTT_HOST') is not None:
        MQTT_HOST = os.getenv('MQTT_HOST')

    if os.getenv('MQTT_PORT') is not None:
        MQTT_PORT = int(os.getenv('MQTT_PORT'))

    if os.getenv('MODBUS_HOST') is not None:
        MODBUS_HOST = os.getenv('MODBUS_HOST')

    if os.getenv('MODBUS_PORT') is not None:
        MODBUS_PORT = int(os.getenv('MODBUS_PORT'))

    if os.getpid() == 1:
        signal.signal(signal.SIGINT, terminate)
        signal.signal(signal.SIGTERM, terminate)
        signal.signal(signal.SIGQUIT, terminate)

    main(16)  # process 16 coils
